version: "3"

services:
  blog_db:
    container_name: blog_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
  blog_web:
    container_name: blog_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    depends_on:
      - blog_db
